[theme]
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
primaryColor = "#FF4B4B"
font = "sans serif"

[client]
# Add borders and other styling
toolbarMode = "auto"
showSidebarNavigation = true

[runner]
# Control spacing and layout
magicEnabled = true